#!/bin/bash
# 
# NAME
#   aecho - Displays arguments explicitely
# 
# SYNOPSYS
#   aecho [ARGUMENTS]...
# 
# DESCRIPTION
#   All arguments are printed explicitely.   
#
# EXAMPLE
#   The following 
# 
#     aecho lorem "ipsum dolor"
# 
#   prints
#
#     arg 1: 'lorem'
#     arg 2: 'ipsum dolor'
# 

N=1
for a in "$@"; do
  echo "arg $N: '$a'"
  N=$((N+1))
done