#!/bin/bash
. git-common-demo
gdr "git init"
gdr "echo hello >main.cpp"
gdr "git add main.cpp"
gdr "git commit -m 'initial commit'"
gdr "echo world >>main.cpp"
gdr "git commit -am 'added world'"
gdr "git checkout -b featureX master^" \
    "I.e. create and checkout a new branch pointing to the first parent of master"
gdr "echo switzerland >> main.cpp"
gdr "git commit -am 'added switzerland'"
gdr "git rebase master featureX" \
    "$MSG_CONFLICT"
gdr "echo $'hello\nworld and switzerland' >main.cpp" \
    "$MSG_RESOLVE_CONFLICT"
gdr "git add main.cpp" \
    "$MSG_RESOLVED_CONFLICTS"
gdr "git rebase --continue" \
    "After resolving all conflicts, continue/finish the rebase"

