#!/bin/bash

. ansi_escape_codes

echo -e "${BWhi}Demonstrates that Git references are really simple:${RCol}"
cat <<EOF
- The (fully qualified) name of a reference is the path of a file (ignoring
  packed references).
- The content of that file is the content of the reference, which is either
  - the id of an Git object
  - the (fully qualified) name of an reference

EOF

if ! which tree >/dev/null; then
  echo "Command 'tree' not found. If you have apt: sudo apt-get install tree" >2
  exit 1
fi

if [ -d .git ]; then
  cd .git
fi

echo -e "${BWhi}Filetree of reference related files (ignoring packed refs) in the .git directory:${RCol}"
tree -n --noreport refs
ls -1 *HEAD
echo

echo -e "${BWhi}Content of files:${RCol}"
{ find refs -type f; ls *HEAD; } |
  grep -v FETCH_HEAD | # is actually not a single ref but a collection of refs
  while read refname; do
    echo -en "${Blu}$refname: ${RCol}"
    cat "$refname"
  done
