#!/bin/bash
# Harmonizes all these dates: file modification data, all dates in the exiv
# meta data.
  
find -maxdepth 1 -type f |
  while read f ; do
    d=$(perl -pe 's/^.*?([0-9]{8})T([0-9]{4})([0-9]{2}).*$/\1\2.\3/x' <<< "$f" )
    touch "$f" -t "$d" ;
    exiftool -P -overwrite_original '-FileModifyDate>AllDates' "$f"
  done
