#!/bin/bash
#
# NAME
#   meld-wrapper - invoke multiple meld instances with multiple tabs each
#
# SYNOPSIS
#   meld-wrapper <base> <local> <remote> <merged>
#
# DESCRIPTION
#   Invokes two meld windows, the first having tabs involving <merged> <local>
#   <remote>, the second having tabs involving <base> <local>
#   <merged>. I.e. the first window is about editing the correct merge result
#   in <merged>, and the second window is about seeing the two changes <base>
#   -> <local> and <base> -> <remote>.
#
#   Makes all files except <merged> readonly before running meld, WITHOUT
#   returning them back to their previous file mode after this script
#   exits. The intention is that the user does not accidentally change these
#   files because he confused which file is which in the merge tool.
#
#   The returned exit code is undefined.


BASE="$1"
LOCAL="$2"
REMOTE="$3"
MERGED="$4"

chmod a-w "$BASE" "$LOCAL" "$REMOTE"

meld "$LOCAL" "$MERGED" "$REMOTE" \
  --diff "$LOCAL" "$MERGED" \
  --diff "$MERGED" "$REMOTE" &
PID1=$!
meld --diff "$BASE" "$REMOTE" \
  --diff "$LOCAL" "$BASE" &
PID2=$!
wait $PID1 $PID2
