#!/bin/bash
#
# NAME
#   meld-wrapper - invoke multiple meld instances with multiple tabs each
#
# SYNOPSIS
#   meld-wrapper <base> <local> <remote> <merged>
#
# DESCRIPTION
#   Invokes two meld windows, the first having tabs involving <merged> <local>
#   <remote>, the second having tabs involving <base> <local>
#   <merged>. I.e. the first window is about editing the correct merge result
#   in <merged>, and the second window is about seeing the two changes <base>
#   -> <local> and <base> -> <remote>.
#
#   The returned exit code is undefined.


BASE="$1"
LOCAL="$2"
REMOTE="$3"
MERGED="$4"

meld --diff "$BASE" "$REMOTE" \
     --diff "$BASE" "$LOCAL" &
PID2=$!

meld --diff "$LOCAL" "$MERGED" \
     --diff "$REMOTE" "$MERGED" &
PID1=$!

wait $PID1 $PID2
