#!/bin/bash
BASE="$1"
LOCAL="$2"
REMOTE="$3"
MERGED="$4"
chmod a-w "$BASE" "$LOCAL" "$REMOTE"
meld --diff "$LOCAL" "$MERGED" "$REMOTE" \
     --diff "$LOCAL" "$MERGED" \
     --diff "$BASE" "$REMOTE" \
     --diff "$MERGED" "$REMOTE" \
     --diff "$BASE" "$LOCAL"
