#!/bin/bash
# - makes all files except $MERGED readonly
# - makes git always ask whether the merge was successfull (precondition:
#   mergetool.<tool>.trustExitCode is set to false)

MERGE_TOOL="$1"
BASE="$2"
LOCAL="$3"
REMOTE="$4"
MERGED="$5"

MERGED_TIMESTAMP=$(stat -c "%Y" "$MERGED")
chmod a-w "$BASE" "$LOCAL" "$REMOTE"
"$MERGE_TOOL" "$BASE" "$LOCAL" "$REMOTE" "$MERGED"
touch -d "@$MERGED_TIMESTAMP" "$MERGED"
exit 0
