#!/bin/bash
# - makes all files except $MERGED readonly
# - makes git always ask whether the merge was successfull (precondition:
#   mergetool.<tool>.trustExitCode is set to false)

function mergetool {
  # meld "$LOCAL" "$MERGED" "$REMOTE" --auto-merge

  # meld --diff "$LOCAL" "$MERGED" "$REMOTE" \
  #    --diff "$LOCAL" "$MERGED" \
  #    --diff "$BASE" "$REMOTE" \
  #    --diff "$MERGED" "$REMOTE" \
  #    --diff "$LOCAL" "$BASE"

  meld --diff "$LOCAL" "$MERGED" "$REMOTE" \
     --diff "$LOCAL" "$MERGED" \
     --diff "$MERGED" "$REMOTE" &
  PID1=$!
  sleep 0.1
  meld --diff "$BASE" "$REMOTE" \
     --diff "$LOCAL" "$BASE" &
  PID2=$!

  wait $PID1 $PID2
}

BASE="$1"
LOCAL="$2"
REMOTE="$3"
MERGED="$4"

MERGED_TIMESTAMP=$(stat -c "%Y" "$MERGED")
chmod a-w "$BASE" "$LOCAL" "$REMOTE"
mergetool
touch -d "@$MERGED_TIMESTAMP" "$MERGED"
exit 0
